workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    instance_type: mac_mini_m1
    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Install npm dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Install Expo CLI and eject
        script: |
          npm install -g expo-cli
          npx expo prebuild
          expo eject
      - name: Set up app/build.gradle
        script: |
          mv ./support-files/build.gradle android/app
    artifacts:
      - android/app/build/outputs/**/*.aab
